### ISSUE TITLE
Error getting invoice detail

### ISSUE THREAD

**Issue by ventur40** [zoho/zohocrm-python-sdk-6.0#16]
Hello I'm using zoho API  to get invoices and I'm getting an error  when requesting an invoice detail:

```
[2024-08-02 12:45:50,131] [INFO] [SDKLogger] GET - URL = https://www.zohoapis.com/crm/v6/Invoices/4228798000270666805 , HEADERS = {"Authorization": " ## can't disclose ## ", "X-ZOHO-SDK": "Linux/5.15.0-117-generic/python-6.0/3.11.3:6.0.0"} , PARAMS = {}.
[2024-08-02 12:45:50,139] [DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): www.zohoapis.com:443
[2024-08-02 12:45:51,605] [DEBUG] [urllib3.connectionpool] https://www.zohoapis.com:443 "GET /crm/v6/Invoices/4228798000270666805 HTTP/1.1" 200 None
[2024-08-02 12:46:03,511] [ERROR] [SDKLogger] Exception in current API call execution : Caused By: None - 'NoneType' object has no attribute 'items'
```

```
This is the complete traceback:
Traceback (most recent call last):
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/common_api_handler.py", line 271, in api_call
    return_object = convert_instance.get_wrapped_response(response, class_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 442, in get_wrapped_response
    return self.get_response(response.json(), pack)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 468, in get_response
    instance = self.find_match(classes, response_json)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 691, in find_match
    return self.get_response(response_json, pack)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 485, in get_response
    instance = self.not_record_response(instance=instance, class_name=class_name,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 496, in not_record_response
    member_value = self.get_data(key_data, key_detail)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 565, in get_data
    return self.get_data_value(data_type, key_data, member_detail)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 571, in get_data_value
    member_value = self.get_collections_data(key_data, member_detail)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 636, in get_collections_data
    values.append(self.get_response(response, pack))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 481, in get_response
    instance = self.is_record_response(response_json, class_detail, package_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 550, in is_record_response
    key_value = self.get_data(key_data, key_detail)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 565, in get_data
    return self.get_data_value(data_type, key_data, member_detail)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 571, in get_data_value
    member_value = self.get_collections_data(key_data, member_detail)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 631, in get_collections_data
    values.append(self.is_record_response(response, self.__get_module_detail_from_user_spec_json(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/json_converter.py", line 519, in is_record_response
    for key, value in class_detail.items():
                      ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ventur40/projects/orders-backend-rlh/orders/utils/rlh/api_connector.py", line 141, in get_record
    response = record_operations.get_record(record_id, param_instance, header_instance)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/record/record_operations.py", line 80, in get_record
    return handler_instance.api_call(ResponseHandler.__module__, 'application/json')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ventur40/.local/share/virtualenvs/orders-backend-rlh-Xe-N1X-h/lib/python3.11/site-packages/zohocrmsdk/src/com/zoho/crm/api/util/common_api_handler.py", line 282, in api_call
    raise sdk_exception
zohocrmsdk.src.com.zoho.crm.api.exception.sdk_exception.SDKException: Caused By: None - 'NoneType' object has no attribute 'items'
```

**Comment by raja-7453** [comment]
@ventur40 Please get in touch with [support@zohocrm.com](mailto:support@zohocrm.com), for further updates. We will follow up on this request, over there.

Thanks!
